// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TransactionEFDAL.DataAccess;

#nullable disable

namespace TransactionEFDAL.Migrations
{
    [DbContext(typeof(TransactionDbContext))]
    [Migration("20241001152139_2024-10-01-InitialMigraion")]
    partial class _20241001InitialMigraion
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("TransactionEFDAL.Models.Transaction", b =>
                {
                    b.Property<Guid>("TransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Amount")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorMsg")
                        .HasColumnType("TEXT");

                    b.Property<string>("EtheriumProof")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("FeeFrom")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("FeeTo")
                        .HasColumnType("TEXT");

                    b.Property<string>("TokenFromOld")
                        .HasColumnType("TEXT");

                    b.Property<string>("TokenToOld")
                        .HasColumnType("TEXT");

                    b.Property<int>("TokenType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TransactionIniciator")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TransactionSignature")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TransactionStatus")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TransactionType")
                        .HasColumnType("INTEGER");

                    b.HasKey("TransactionId");

                    b.ToTable("Transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
