// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WalletEFDAL.DataAccess;

#nullable disable

namespace WalletEFDAL.Migrations
{
    [DbContext(typeof(WalletDbContext))]
    [Migration("20241001144809_2024-10-01-InitialMigraion")]
    partial class _20241001InitialMigraion
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("WalletEFDAL.Models.Token", b =>
                {
                    b.Property<Guid>("TokenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("TokenData")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TokenDataSignature")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TokenIdHash")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("WalletAddress")
                        .HasColumnType("TEXT");

                    b.Property<int>("WalletAddressHash")
                        .HasColumnType("INTEGER");

                    b.HasKey("TokenId");

                    b.HasIndex("WalletAddress");

                    b.ToTable("Tokens");
                });

            modelBuilder.Entity("WalletEFDAL.Models.Wallet", b =>
                {
                    b.Property<Guid>("Address")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.HasKey("Address");

                    b.ToTable("Wallets");
                });

            modelBuilder.Entity("WalletEFDAL.Models.Token", b =>
                {
                    b.HasOne("WalletEFDAL.Models.Wallet", "Wallet")
                        .WithMany("Tokens")
                        .HasForeignKey("WalletAddress")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Wallet");
                });

            modelBuilder.Entity("WalletEFDAL.Models.Wallet", b =>
                {
                    b.Navigation("Tokens");
                });
#pragma warning restore 612, 618
        }
    }
}
